//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_CellPhoneStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string OrderID { get; set; }
        public string ProductVersionID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ProductVersion ProductVersion { get; set; }
    }
}
