//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_CellPhoneStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public string OrderID { get; set; }
        public string Payment { get; set; }
        public string Delivery { get; set; }
        public string Notes { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int IntoMoney { get; set; }
        public string CustomerID { get; set; }
        public int OrderStateID { get; set; }
        public int DeliveryStateID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DeliveryState DeliveryState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual OrderState OrderState { get; set; }
    }
}
