//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_CellPhoneStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductVersions = new HashSet<ProductVersion>();
        }
    
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string BrandID { get; set; }
        public string Size { get; set; }
        public string Weight { get; set; }
        public string SIM { get; set; }
        public string ScreenType { get; set; }
        public string ScreenSize { get; set; }
        public string ScreenResolution { get; set; }
        public string OperatingSystem { get; set; }
        public string Chipset { get; set; }
        public string CPU { get; set; }
        public string GPU { get; set; }
        public string SDCard { get; set; }
        public string BackCamera { get; set; }
        public string FrontCamera { get; set; }
        public string WLAN { get; set; }
        public string Bluetooth { get; set; }
        public string GPS { get; set; }
        public string NFC { get; set; }
        public string USB { get; set; }
        public string Sensor { get; set; }
        public string Battery { get; set; }
        public string Image { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual ProductIntroduce ProductIntroduce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVersion> ProductVersions { get; set; }
    }
}
